---
title: "ClassificationTree"
author: "Tianbo Qiu"
date: "December 12, 2018"
output: pdf_document
---



```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown

```{r}
data = read.csv("CreditDataRaw.csv",encoding="UTF-8")
names(data)[1] <- "ID"
names(data)[25] <- "Payment" #default.payment.next.month
High = ifelse(data$Payment==0,"NOT","DEFAULT")
data = data.frame(data,High)
set.seed(10)
DATASIZE = dim(data)[1]
train_index = sample(DATASIZE, DATASIZE*0.8)
indicator = rep(0,DATASIZE)
indicator[train_index] = 1 # 1:train 0:valid
data = data.frame(data,indicator)
train = subset(data,data$indicator==1)
valid = subset(data,data$indicator==0)
```

## Artificial Neural Networks
```{r}
# Scale the Feature into the [0,1] interval
scale01 <- function(x){
  (x - min(x)) / (max(x) - min(x))
}
train_norm = train
valid_norm = valid
for(name in names(train)){
  if(name != "ID" && name !="Payment" && name != "High"  && name != "indicator"){
    train_norm[name] <- scale01(train_norm[name])
    valid_norm[name] <- scale01(valid_norm[name])
  }
  
}


```

```{r}
library(neuralnet)
# set up ANN formula
names = names(train)
f <- as.formula(paste("Payment ~", paste(names[!names %in% c("Payment","ID", "indicator","High")], collapse = " + ")))

```

```{r}
net <- neuralnet(f, data=train_norm, hidden = c(3,2),act.fct = "logistic",linear.output = FALSE,lifesign = "full",threshold = 0.05)

#net <- neuralnet(f, data=train_norm, hidden = 20,act.fct = "logistic",linear.output = FALSE,lifesign = "full",threshold = 0.05)

```


```{r}
xx = train_norm
xx["ID"] <- NULL
xx["Payment"] <- NULL
xx["High"] <- NULL
xx["indicator"] <- NULL
ret = compute(net, xx)
result = data.frame(actual = train_norm$Payment, prediction = ret$net.result)
rounded_result = sapply(result,round,digits=0)
rounded_result = data.frame(rounded_result)
tt = table(rounded_result)
error_train = 1 - sum(diag(tt)) / sum(tt)
error_train

```
```{r}
xxv = valid_norm
xxv["ID"] <- NULL
xxv["Payment"] <- NULL
xxv["High"] <- NULL
xxv["indicator"] <- NULL
retv = compute(net, xxv)
resultv = data.frame(actual = valid_norm$Payment, prediction = retv$net.result)
rounded_resultv = sapply(resultv,round,digits=0)
rounded_resultv = data.frame(rounded_resultv)
ttv = table(rounded_resultv)
error_valid = 1 - sum(diag(ttv)) / sum(ttv)
error_valid
```

```{r}
# training error
predL = predict(net,train_norm,type="class")
tt = table(train$High, predL)
error_train = 1 - sum(diag(tt)) / sum(tt)
error_train

# validation error
predLV = predict(net,valid_norm,type="class")
tv = table(valid$High,predLV)
error_valid = 1 - sum(diag(tv)) /  sum(tv)
error_valid
```


